---
- name: Join Worker Nodes to Kubernetes Cluster (match manual guide)
  hosts: k8s_workers
  become: yes
  tasks:
    - name: Obtain join command from master (file or generate)
      shell: cat /tmp/k8s-join-command || kubeadm token create --print-join-command
      delegate_to: k8s-master
      register: join_cmd
      run_once: true

    - name: Store join command as fact on master for global access
      set_fact:
        k8s_join_command: "{{ join_cmd.stdout | trim }}"
      delegate_to: k8s-master
      delegate_facts: true
      run_once: true

    - name: Check if node is already part of cluster
      stat:
        path: /etc/kubernetes/kubelet.conf
      register: kubelet_conf

    - name: Join worker node to cluster
      command: "{{ hostvars['k8s-master'].k8s_join_command }}"
      when: not kubelet_conf.stat.exists
      register: join_result

    - name: Display join result
      debug:
        msg: "Worker node {{ inventory_hostname }} joined cluster successfully"
      when: join_result is succeeded

    - name: Ensure kubelet is running
      systemd:
        name: kubelet
        state: started
        enabled: yes
